### ISSUE TITLE
jsonrpc not specifically going to any if statement

### ISSUE THREAD

**Issue by yesnice** [Tasha53505/159.356-capstone-project-group#93]
I have no idea what is going and how all my jsonrpc requests (that aren't arrays) have worked but it seems all of the requests aren't going anywhere specifically as none of the console.logs are actually doing anything, and I don't have the time to create one for EVERY area in that file. I need to have it working as I need to be able to change a value in an array in the preferences

**Comment by daKonrad2000** [comment]
Need to check if jsonrpc is used anywhere else, but it is not needed for settings anymore, could possibly be removed
